repos:
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
  - repo: https://github.com/terraform-linters/tflint
    rev: v0.44.1
    hooks:
      - id: tflint
  - repo: https://github.com/tfsec/tfsec
    rev: v1.28.1
    hooks:
      - id: tfsec
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.75.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_docs
